server:
  port: 8888

###
#Classpath and file-based solution
###

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/,
                            classpath:config/licensing,
                            classpath:config/organization,
                            classpath:config/registry,
                            classpath:config/gateway
#         search-locations: file://<chapter_2>/config/src/main/resources/config/licensing