example:
  property: "I AM IN THE DEFAULT"

spring:
  jpa:
    database: "h2"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
  database:
    driverClassName: "org.h2.Driver"
  datasource:
    platform:  "h2"
    url: "jdbc:h2:mem:eagle_eye"
#    url: "jdbc:postgresql://database:5432/eagle_eye_local"
#    username: "postgres"
#    password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"
