server:
  port: 8040

eureka:
  instance:
    hostname: admin
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix: WARN
      gelerion: DEBUG
    org:
      springframework:
        web: WARN