server:
  port: 8081

example:
  property: "I AM IN THE DEFAULT"

spring:
  jpa:
    database: "h2"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        ddl-auto: none
  database:
    driverClassName: "org.h2.Driver"
  datasource:
    platform:  "h2"
    url: "jdbc:h2:mem:eagle_eye"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  h2:
    console:
      enabled: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user

logging:
  level:
    com:
      netflix: WARN
      gelerion: DEBUG
    org:
      springframework:
        web: WARN